from __future__ import annotations

from collections.abc import Mapping
from typing import Any

DEFAULT_LANGUAGE = "EN"
SUPPORTED_LANGUAGES = (
    ("EN", "English", "Use English interface text"),
    ("KO", "한국어", "한국어 인터페이스 문구를 사용합니다"),
)

_EN: dict[str, str] = {
    # Shared
    "ui.language": "Language",
    "ui.on": "On",
    "ui.off": "Off",
    # Transform gizmo
    "gizmo.title": "Gizmo Options",
    "gizmo.section.general": "General",
    "gizmo.section.rotate": "Rotate",
    "gizmo.section.move": "Move",
    "gizmo.section.scale": "Scale",
    "gizmo.overall_size": "Gizmo Size",
    "gizmo.zoom_keep_size": "Keep Size on Zoom",
    "gizmo.zoom_out_max": "Zoom-Out Limit",
    "gizmo.rotate_axis_thickness": "Ring Thickness",
    "gizmo.rotate_outer_thickness": "Outer Ring Thickness",
    "gizmo.rotate_outer_distance": "Outer Ring Gap",
    "gizmo.rotate_free_sensitivity": "Free Rotate Sensitivity",
    "gizmo.rotate_snap_angle": "Snap Angle",
    "gizmo.rotate_show_angle": "Show Angle",
    "gizmo.move_axis_thickness": "Line Thickness",
    "gizmo.move_arrow_length": "Arrow Length",
    "gizmo.move_arrow_tip": "Arrow Tip Size",
    "gizmo.move_plane_box": "Plane Box Size",
    "gizmo.scale_axis_thickness": "Line Thickness",
    "gizmo.scale_axis_length": "Axis Length",
    "gizmo.scale_axis_box": "End Box Size",
    "gizmo.scale_center_box": "Center Box Size",
    "gizmo.axis_colors": "Axis Colors",
    "gizmo.tip.overall_size": "Changes the overall gizmo size.",
    "gizmo.tip.zoom_keep_size": "Keeps the gizmo closer to the same screen size while zooming.",
    "gizmo.tip.zoom_out_max": "Sets how large the gizmo can get when zoomed far out.",
    "gizmo.tip.rotate_axis_thickness": "Changes the thickness of the X, Y, and Z rotation rings.",
    "gizmo.tip.rotate_outer_thickness": "Changes the thickness of the outer rotation ring.",
    "gizmo.tip.rotate_outer_distance": "Changes the gap between the outer ring and the axis rings.",
    "gizmo.tip.rotate_free_sensitivity": "Changes how quickly Free Rotate responds to mouse movement.",
    "gizmo.tip.rotate_colors": "Changes the X, Y, Z, and outer ring colors.",
    "gizmo.tip.rotate_snap_angle": "Sets the angle step used while rotating.",
    "gizmo.tip.rotate_show_angle": "Shows or hides the current angle while rotating.",
    "gizmo.tip.move_axis_thickness": "Changes the thickness of the move lines.",
    "gizmo.tip.move_arrow_length": "Changes the move arrow length.",
    "gizmo.tip.move_arrow_tip": "Changes the size of the move arrow tips.",
    "gizmo.tip.move_plane_box": "Changes the size of the two-axis move boxes.",
    "gizmo.tip.move_colors": "Changes the X, Y, and Z move colors.",
    "gizmo.tip.scale_axis_thickness": "Changes the thickness of the scale lines.",
    "gizmo.tip.scale_axis_length": "Changes the length of the scale axes.",
    "gizmo.tip.scale_axis_box": "Changes the size of the boxes at the ends of the scale axes.",
    "gizmo.tip.scale_center_box": "Changes the center box used to scale all axes together.",
    "gizmo.tip.scale_colors": "Changes the X, Y, and Z scale colors.",
    # Main panel
    "panel.track_bar": "Track Bar",
    "panel.start": "Start",
    "panel.end": "End",
    "panel.keying": "Keying",
    "panel.position_short": "Pos",
    "panel.rotation_short": "Rot",
    "panel.scale": "Scale",
    "panel.set_key": "Set Key",
    "panel.key_mode": "Key Mode",
    "panel.auto": "Auto",
    "panel.trajectory": "Trajectory",
    "panel.live": "Live",
    "panel.refresh": "Refresh",
    "panel.edit": "Edit",
    "panel.tangents": "Tangents",
    "panel.add_key": "Add Key",
    # Rigped workflow
    "rigped.workflow": "Rigped Workflow",
    "rigped.new": "New Rigped",
    "rigped.select": "Select",
    "rigped.fit": "Fit",
    "rigped.animate": "Animate",
    "rigped.apply_fit": "Apply Fit",
    "rigped.reset_fit": "Reset Fit",
    "rigped.fit_mode": "Fit Mode",
    "rigped.current": "Current Rigped",
    "rigped.status.animate": "Animate",
    "rigped.status.select": "Select",
    "rigped.fit_hint": "Adjust joints to match the character",
    "rigped.create_hint": "Click to place · move vertically to size · click again to confirm",
    "rigped.select_hint": "Use Select to choose another Rigped or object",
    "rigped.transform.refused": "This Rigped transform is not supported in the current selection/state",
    "rigped.transform.semantic_move": "This Rigped Move requires AWB semantic kinematic control; native Move is blocked",
    "rigped.transform.orientation_unsupported": "Rigped semantic Move supports Global, Local, and View orientations",
    "rigped.contact.title": "Contact",
    "rigped.contact.world": "World",
    "rigped.contact.object_space": "Object",
    "rigped.contact.object": "Contact Object",
    "rigped.contact.bind": "Bind Object",
    "rigped.contact.clear": "Clear",
    "rigped.contact.object_hint": "Bind one Object to the selected hand/foot, then Planted follows that Object",
    "rigped.contact.point": "Contact Point (Local)",
    "rigped.contact.replant": "Replant",
    "rigped.contact.replanted": "Contact replanted",
    "rigped.contact.object_point_hint": "Object Contact currently supports the terminal origin point; arbitrary points use World Contact",
    "rigped.contact.object_bound": "Contact Object bound",
    "rigped.contact.object_cleared": "Contact Object cleared",
    "rigped.orientation_cycle": "Transform Orientation Cycle",
    "rigped.orientation.global": "Global",
    "rigped.orientation.local": "Local",
    "rigped.orientation.normal": "Normal",
    "rigped.orientation.gimbal": "Gimbal",
    "rigped.orientation.view": "View",
    "rigped.orientation.cursor": "Cursor",
    "rigped.picker.title": "Body Picker",
    "rigped.picker.suffix.ik": "IK",
    "rigped.picker.suffix.pole": "Pole",
    "rigped.picker.root": "Root",
    "rigped.picker.com": "COM",
    "rigped.picker.pelvis": "Pelvis",
    "rigped.picker.spine": "Spine",
    "rigped.picker.neck": "Neck",
    "rigped.picker.head": "Head",
    "rigped.picker.clavicle": "Clavicle",
    "rigped.picker.arm": "Arm",
    "rigped.picker.upper_arm": "Upper Arm",
    "rigped.picker.forearm": "Forearm",
    "rigped.picker.hand": "Hand",
    "rigped.picker.leg": "Leg",
    "rigped.picker.thigh": "Thigh",
    "rigped.picker.calf": "Calf",
    "rigped.picker.foot": "Foot",
    "rigped.picker.toe": "Toe",
    "rigped.create_header.place": "New Rigped  |  Click anywhere to place default 1.8m Rigped  |  Esc/RMB cancel",
    "rigped.create_header.release": "New Rigped  Height 1.800  |  Release LMB, then move vertically to resize",
    "rigped.create_header.size": "New Rigped  Height {height:.3f}  |  Move mouse vertically to resize  |  LMB confirm  |  Esc/RMB cancel",
    "rigped.create_preview.place": "Click anywhere to place a default Rigped",
    "rigped.create_preview.height": "Rigped Height  {height:.3f}",
    "rigped.create_preview.controls": "Move vertically · LMB confirm · Esc/RMB cancel",
    # Rigped tooltips — short, user-facing actions only.
    "tooltip.rigped.new": "Create a new Rigped",
    "tooltip.rigped.select": "Select a Rigped or another object",
    "tooltip.rigped.fit": "Adjust the Rigped body shape and joint positions",
    "tooltip.rigped.animate": "Animate the selected Rigped",
    "tooltip.rigped.apply_fit": "Apply the current body-shape changes",
    "tooltip.rigped.reset_fit": "Restore the state from before this Fit began",
}

_KO: dict[str, str] = {
    # Shared
    "ui.language": "언어",
    "ui.on": "켜기",
    "ui.off": "끄기",
    # Transform gizmo
    "gizmo.title": "기즈모 설정",
    "gizmo.section.general": "공통",
    "gizmo.section.rotate": "회전",
    "gizmo.section.move": "이동",
    "gizmo.section.scale": "크기",
    "gizmo.overall_size": "기즈모 크기",
    "gizmo.zoom_keep_size": "줌 크기 유지",
    "gizmo.zoom_out_max": "줌아웃 크기 제한",
    "gizmo.rotate_axis_thickness": "링 두께",
    "gizmo.rotate_outer_thickness": "바깥 링 두께",
    "gizmo.rotate_outer_distance": "바깥 링 간격",
    "gizmo.rotate_free_sensitivity": "프리 회전 감도",
    "gizmo.rotate_snap_angle": "스냅 각도",
    "gizmo.rotate_show_angle": "각도 표시",
    "gizmo.move_axis_thickness": "선 두께",
    "gizmo.move_arrow_length": "화살표 길이",
    "gizmo.move_arrow_tip": "화살촉 크기",
    "gizmo.move_plane_box": "평면 박스 크기",
    "gizmo.scale_axis_thickness": "선 두께",
    "gizmo.scale_axis_length": "축 길이",
    "gizmo.scale_axis_box": "끝 박스 크기",
    "gizmo.scale_center_box": "중앙 박스 크기",
    "gizmo.axis_colors": "축 색상",
    "gizmo.tip.overall_size": "기즈모 전체 크기를 바꿉니다.",
    "gizmo.tip.zoom_keep_size": "화면을 확대하거나 축소해도 기즈모가 비슷한 크기로 보이게 합니다.",
    "gizmo.tip.zoom_out_max": "화면을 멀리 축소했을 때 기즈모가 커질 수 있는 최대 크기를 정합니다.",
    "gizmo.tip.rotate_axis_thickness": "X, Y, Z 회전 링의 두께를 바꿉니다.",
    "gizmo.tip.rotate_outer_thickness": "바깥쪽 회전 링의 두께를 바꿉니다.",
    "gizmo.tip.rotate_outer_distance": "바깥 링과 축 링 사이의 간격을 바꿉니다.",
    "gizmo.tip.rotate_free_sensitivity": "빈 공간을 드래그할 때 프리 회전이 마우스 움직임에 반응하는 속도를 바꿉니다.",
    "gizmo.tip.rotate_colors": "X, Y, Z 축 링과 바깥 링의 색을 바꿉니다.",
    "gizmo.tip.rotate_snap_angle": "회전할 때 맞춰지는 각도 단위를 정합니다.",
    "gizmo.tip.rotate_show_angle": "회전 중 현재 각도 표시를 켜거나 끕니다.",
    "gizmo.tip.move_axis_thickness": "이동 축 선의 두께를 바꿉니다.",
    "gizmo.tip.move_arrow_length": "이동 화살표 길이를 바꿉니다.",
    "gizmo.tip.move_arrow_tip": "이동 화살촉 크기를 바꿉니다.",
    "gizmo.tip.move_plane_box": "두 축을 함께 움직이는 평면 박스 크기를 바꿉니다.",
    "gizmo.tip.move_colors": "X, Y, Z 이동 축의 색을 바꿉니다.",
    "gizmo.tip.scale_axis_thickness": "크기 축 선의 두께를 바꿉니다.",
    "gizmo.tip.scale_axis_length": "크기 축의 길이를 바꿉니다.",
    "gizmo.tip.scale_axis_box": "크기 축 끝에 있는 박스의 크기를 바꿉니다.",
    "gizmo.tip.scale_center_box": "모든 축의 크기를 함께 바꾸는 중앙 박스 크기를 바꿉니다.",
    "gizmo.tip.scale_colors": "X, Y, Z 크기 축의 색을 바꿉니다.",
    # Main panel
    "panel.track_bar": "트랙 바",
    "panel.start": "시작",
    "panel.end": "끝",
    "panel.keying": "키 설정",
    "panel.position_short": "위치",
    "panel.rotation_short": "회전",
    "panel.scale": "크기",
    "panel.set_key": "Set Key",
    "panel.key_mode": "키 모드",
    "panel.auto": "자동",
    "panel.trajectory": "궤적",
    "panel.live": "실시간",
    "panel.refresh": "새로고침",
    "panel.edit": "편집",
    "panel.tangents": "탄젠트",
    "panel.add_key": "키 추가",
    # Rigped workflow
    "rigped.workflow": "Rigped 작업",
    "rigped.new": "새 Rigped",
    "rigped.select": "선택",
    "rigped.fit": "핏",
    "rigped.animate": "애니메이션",
    "rigped.apply_fit": "핏 적용",
    "rigped.reset_fit": "핏 초기화",
    "rigped.fit_mode": "핏 모드",
    "rigped.current": "현재 Rigped",
    "rigped.status.animate": "애니메이션",
    "rigped.status.select": "선택",
    "rigped.fit_hint": "캐릭터에 맞게 관절을 조정합니다",
    "rigped.create_hint": "클릭해 배치 · 위아래로 크기 조절 · 다시 클릭해 확정",
    "rigped.select_hint": "선택을 눌러 다른 Rigped나 오브젝트를 고릅니다",
    "rigped.transform.refused": "현재 선택/상태에서는 이 Rigped 변형을 사용할 수 없습니다",
    "rigped.transform.semantic_move": "이 Rigped 이동은 AWB 시맨틱 키네마틱 제어가 필요하여 기본 Move를 차단합니다",
    "rigped.transform.orientation_unsupported": "Rigped 시맨틱 이동은 글로벌, 로컬, 뷰 방향을 지원합니다",
    "rigped.contact.title": "컨택트",
    "rigped.contact.world": "월드",
    "rigped.contact.object_space": "오브젝트",
    "rigped.contact.object": "컨택트 오브젝트",
    "rigped.contact.bind": "오브젝트 연결",
    "rigped.contact.clear": "해제",
    "rigped.contact.object_hint": "선택한 손/발에 오브젝트 하나를 연결하면 Planted가 그 오브젝트를 따라갑니다",
    "rigped.contact.point": "컨택트 포인트 (로컬)",
    "rigped.contact.replant": "다시 고정",
    "rigped.contact.replanted": "컨택트 포인트를 다시 고정했습니다",
    "rigped.contact.object_point_hint": "오브젝트 컨택트는 현재 터미널 원점만 지원합니다. 임의 포인트는 월드 컨택트를 사용합니다",
    "rigped.contact.object_bound": "컨택트 오브젝트를 연결했습니다",
    "rigped.contact.object_cleared": "컨택트 오브젝트 연결을 해제했습니다",
    "rigped.orientation_cycle": "변형 축 방향 순환",
    "rigped.orientation.global": "글로벌",
    "rigped.orientation.local": "로컬",
    "rigped.orientation.normal": "노멀",
    "rigped.orientation.gimbal": "짐벌",
    "rigped.orientation.view": "뷰",
    "rigped.orientation.cursor": "커서",
    "rigped.picker.title": "바디 피커",
    "rigped.picker.suffix.ik": "IK",
    "rigped.picker.suffix.pole": "폴",
    "rigped.picker.root": "루트",
    "rigped.picker.com": "중심",
    "rigped.picker.pelvis": "골반",
    "rigped.picker.spine": "척추",
    "rigped.picker.neck": "목",
    "rigped.picker.head": "머리",
    "rigped.picker.clavicle": "쇄골",
    "rigped.picker.arm": "팔",
    "rigped.picker.upper_arm": "위팔",
    "rigped.picker.forearm": "아래팔",
    "rigped.picker.hand": "손",
    "rigped.picker.leg": "다리",
    "rigped.picker.thigh": "허벅지",
    "rigped.picker.calf": "종아리",
    "rigped.picker.foot": "발",
    "rigped.picker.toe": "발끝",
    "rigped.create_header.place": "새 Rigped  |  원하는 위치를 클릭해 기본 1.8m Rigped 배치  |  Esc/RMB 취소",
    "rigped.create_header.release": "새 Rigped  높이 1.800  |  LMB를 놓은 뒤 위아래로 움직여 크기 조절",
    "rigped.create_header.size": "새 Rigped  높이 {height:.3f}  |  위아래로 크기 조절  |  LMB 확정  |  Esc/RMB 취소",
    "rigped.create_preview.place": "원하는 위치를 클릭해 기본 Rigped를 배치합니다",
    "rigped.create_preview.height": "Rigped 높이  {height:.3f}",
    "rigped.create_preview.controls": "위아래로 크기 조절 · LMB 확정 · Esc/RMB 취소",
    # Rigped tooltips — short, user-facing actions only.
    "tooltip.rigped.new": "새 Rigped를 생성합니다",
    "tooltip.rigped.select": "Rigped나 다른 오브젝트를 선택합니다",
    "tooltip.rigped.fit": "Rigped의 체형과 관절 위치를 조정합니다",
    "tooltip.rigped.animate": "선택한 Rigped를 애니메이션합니다",
    "tooltip.rigped.apply_fit": "현재 체형 변경을 적용합니다",
    "tooltip.rigped.reset_fit": "이번 Fit 시작 전 상태로 되돌립니다",
}

LANGUAGE_PACKS: Mapping[str, Mapping[str, str]] = {
    "EN": _EN,
    "KO": _KO,
}


def normalize_language(language: Any) -> str:
    value = str(language or DEFAULT_LANGUAGE).upper()
    return value if value in LANGUAGE_PACKS else DEFAULT_LANGUAGE


def language_for_context(context: Any | None) -> str:
    scene = getattr(context, "scene", None) if context is not None else None
    return normalize_language(getattr(scene, "baw_ui_language", DEFAULT_LANGUAGE))


def text(
    key: str,
    context: Any | None = None,
    *,
    language: str | None = None,
    **values: Any,
) -> str:
    """Return localized UI text with English as the permanent fallback."""

    lang = normalize_language(language) if language is not None else language_for_context(context)
    value = LANGUAGE_PACKS.get(lang, _EN).get(key, _EN.get(key, key))
    return value.format(**values) if values else value
